#!/bin/bash
set -e

# ── Set container hostname to agent ID ───────────────────────
AGENT_ID=${AGENT_ID:-"agent-unknown"}
hostname "$AGENT_ID" 2>/dev/null || true
echo "$AGENT_ID" > /etc/hostname 2>/dev/null || true
# Update /etc/hosts so the hostname resolves
echo "127.0.0.1 $AGENT_ID" >> /etc/hosts 2>/dev/null || true

# ── Persist environment for SSH sessions ─────────────────────
# sshd doesn't inherit container env vars, so write them to a
# profile file that gets sourced on every SSH login.
ENV_FILE="/etc/profile.d/agent-env.sh"
echo "# Agent environment variables (auto-generated by entrypoint)" > "$ENV_FILE"
echo 'export PATH="/home/opencode/.bun/bin:$PATH"' >> "$ENV_FILE"
for var in AGENT_ID AWS_BEARER_TOKEN_BEDROCK AWS_REGION AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY \
           BUCKET_ENDPOINT BUCKET_ACCESS_KEY_ID BUCKET_SECRET_ACCESS_KEY BUCKET_NAME BUCKET_REGION; do
    val="${!var:-}"
    if [ -n "$val" ]; then
        echo "export $var=\"$val\"" >> "$ENV_FILE"
    fi
done
chmod 644 "$ENV_FILE"
echo "Environment variables written to $ENV_FILE"

# Also write to opencode user's bashrc for non-login shells
cp "$ENV_FILE" /home/opencode/.agent-env
cat >> /home/opencode/.bashrc << 'BASHRC'
source /home/opencode/.agent-env
# Set terminal title to agent ID
printf "\033]0;${AGENT_ID}\007"
# Set prompt to show agent ID
export PS1='\[\033[1;36m\][$AGENT_ID]\[\033[0m\] \w\$ '
BASHRC
chown opencode:opencode /home/opencode/.agent-env /home/opencode/.bashrc

# Setup SSH authorized keys from environment variable
if [ -n "$SSH_AUTHORIZED_KEYS" ]; then
    echo "$SSH_AUTHORIZED_KEYS" > /home/opencode/.ssh/authorized_keys
    chmod 600 /home/opencode/.ssh/authorized_keys
    chown opencode:opencode /home/opencode/.ssh/authorized_keys
    echo "SSH authorized keys configured"
else
    echo "Warning: SSH_AUTHORIZED_KEYS not set. SSH access will not work."
fi

# Fix workspace permissions (volume mounts as root)
chown opencode:opencode /workspace
echo "Workspace permissions fixed"

# Generate SSH host keys if they don't exist
if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
    ssh-keygen -A
    echo "SSH host keys generated"
fi

# Set agent ID from environment or default
AGENT_ID=${AGENT_ID:-"agent-unknown"}
echo "Starting agent: $AGENT_ID"

# Export agent ID for status server and workspace sync
export AGENT_ID

# Restore workspace from bucket if configured
if [ -n "${BUCKET_ENDPOINT:-}" ]; then
    echo "Restoring workspace from bucket..."
    /usr/local/bin/workspace-sync restore || echo "Workspace restore skipped or failed (non-fatal)"

    echo "Starting workspace sync daemon (every 5 min)..."
    /usr/local/bin/workspace-sync watch &
else
    echo "No bucket configured, workspace sync disabled"
fi

# Start the status server in the background
echo "Starting status server on port 9090..."
/usr/local/bin/status-server &

# Start SSH daemon in foreground
echo "Starting SSH daemon..."
exec /usr/sbin/sshd -D -e
